before_script:
  - rm -rf /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit-operator
  - mkdir -p /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit-operator
  - cp -r ./. /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit-operator
  - cd /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit-operator
  - export PATH=/usr/local/go1.18.3/bin:$PATH
  - export GOROOT=/usr/local/go1.18.3
  - go version

variables:
  PROJECT: "datakit-operator"
  CI_VERSION: "1.0.1"
  TEST_VERSION: "1.999.0"

stages:
  - test
  - build
  - deploy

build:
  stage: build
  resource_group: production
  only:
    - /^.*$/
  script:
    - make clean
    - make

test:
  stage: test
  resource_group: production
  only:
    - /^dev.*$/
  script:
    - make clean
    - make lint
    - make all_test

release-testing:
  stage: deploy
  resource_group: production
  needs: [build, test]
  only:
    - /^dev.*$/
  script:
    - make pub_testing_image

release-stable:
  stage: deploy
  resource_group: production
  needs: [build, test]
  only:
    - master
  script:
    - make pub_image
