# Default values for datakit-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  ## @param repository - string - required
  ## Define the repository to use:
  #
  repository: {{repository}}

  ## @param tag - string - required
  ## Define the Cluster-Agent version to use.
  #
  tag: ""

  ## @param pullPolicy - string - optional
  ## The Kubernetes [imagePullPolicy][] value
  #
  pullPolicy: Always


env:
  ENV_LOG_LEVEL: info
  ENV_SERVER_LISTEN: 0.0.0.0:9543
  ENV_DD_AGENT_HOST: datakit-service.datakit.svc
  ENV_DD_TRACE_AGENT_PORT: "9529"
  ENV_DD_JAVA_AGENT_IMAGE: pubrepo.jiagouyun.com/datakit-operator/dd-lib-java-init:v1.8.4-guance
  ENV_DD_PYTHON_AGENT_IMAGE: pubrepo.jiagouyun.com/datakit-operator/dd-lib-python-init:v1.6.2
  ENV_DD_JS_AGENT_IMAGE: pubrepo.jiagouyun.com/datakit-operator/dd-lib-js-init:v3.9.2
  ENV_LOGFWD_IMAGE: pubrepo.jiagouyun.com/datakit/logfwd:1.5.8


admissionregistration:
  webhooks:
    caBundle: {{CABUNDLE}}


imagePullSecrets: []
nameOverride: ""
fullnameOverride: "datakit-operator"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 443
  targetPort: 9543


  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  limits:
     cpu: 500m
     memory: 1024Mi
  requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
