# Default values for datakit-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  ## @param repository - string - required
  ## Define the repository to use:
  #
  repository: (@REPOSITORY)

  ## @param tag - string - required
  ## Define the Cluster-Agent version to use.
  #
  tag: ""

  ## @param pullPolicy - string - optional
  ## The Kubernetes [imagePullPolicy][] value
  #
  pullPolicy: Always


imagePullSecrets: []
nameOverride: ""
fullnameOverride: "datakit-operator"

admissionregistration:
  webhooks:
    caBundle: (@CABUNDLE)

service:
  type: ClusterIP
  port: 443
  targetPort: 9543

env: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  limits:
     cpu: 500m
     memory: 1024Mi
  requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
