# Default values for datakit-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  ## @param repository - string - required
  ## Define the repository to use:
  #
  repository: (@REPOSITORY)

  ## @param tag - string - required
  ## Define the Cluster-Agent version to use.
  #
  tag: ""

  ## @param pullPolicy - string - optional
  ## The Kubernetes [imagePullPolicy][] value
  #
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "datakit-operator"

admissionregistration:
  webhooks:
    caBundle: (@CABUNDLE)


configmap:
  jsonconfig: |-
    {
        "server_listen": "0.0.0.0:9543",
        "log_level":     "info",
        "admission_inject": {
            "ddtrace": {
                "enabled_namespaces":     [],
                "enabled_labelselectors": [],
                "images": {
                    "java_agent_image": "(@BRAND_REPO_DATAKIT_OPERATOR)/dd-lib-java-init:latest"
                },
                "envs": {
                    "DD_AGENT_HOST":           "datakit-service.datakit.svc.cluster.local",
                    "DD_TRACE_AGENT_PORT":     "9529",
                    "DD_JMXFETCH_STATSD_HOST": "datakit-service.datakit.svc.cluster.local",
                    "DD_JMXFETCH_STATSD_PORT": "8125",
                    "DD_SERVICE":              "{fieldRef:metadata.labels['app']}",
                    "POD_NAME":                "{fieldRef:metadata.name}",
                    "POD_NAMESPACE":           "{fieldRef:metadata.namespace}",
                    "NODE_NAME":               "{fieldRef:spec.nodeName}",
                    "DD_TAGS":                 "pod_name:$(POD_NAME),pod_namespace:$(POD_NAMESPACE),host:$(NODE_NAME)"
                },
                "resources": {
                    "requests": {
                        "cpu":    "100m",
                        "memory": "64Mi"
                    },
                    "limits": {
                       "cpu":    "200m",
                       "memory": "128Mi"
                    }
                }
            },
            "profiler": {
                "enabled_namespaces":     [],
                "enabled_labelselectors": [],
                "images": {
                    "java_profiler_image":   "(@BRAND_REPO_DATAKIT_OPERATOR)/async-profiler:0.5.0",
                    "python_profiler_image": "(@BRAND_REPO_DATAKIT_OPERATOR)/py-spy:0.1.0",
                    "golang_profiler_image": "(@BRAND_REPO_DATAKIT_OPERATOR)/pprof:0.1.0"
                },
                "envs": {
                    "DK_AGENT_HOST":       "datakit-service.datakit.svc",
                    "DK_AGENT_PORT":       "9529",
                    "DK_PROFILE_VERSION":  "1.2.333",
                    "DK_PROFILE_ENV":      "prod",
                    "DK_PROFILE_DURATION": "240",
                    "DK_PROFILE_SCHEDULE": "*/20 * * * *"
                },
                "resources": {
                    "requests": {
                        "cpu":    "100m",
                        "memory": "64Mi"
                    },
                    "limits": {
                       "cpu":    "500m",
                       "memory": "512Mi"
                    }
                }
            },
            "logfwd": {
                "images": {
                    "logfwd_image": "(@BRAND_REPO_DATAKIT)/logfwd:1.80.0"
                },
                "envs": {
                    "LOGFWD_GLOBAL_SERVICE": "{fieldRef:metadata.labels['app']}",
                    "LOGFWD_POD_NAME":       "{fieldRef:metadata.name}",
                    "LOGFWD_POD_NAMESPACE":  "{fieldRef:metadata.namespace}"
                },
                "resources": {
                    "requests": {
                        "cpu":    "100m",
                        "memory": "64Mi"
                    },
                    "limits": {
                       "cpu":    "500m",
                       "memory": "512Mi"
                    }
                }
            }
        },
        "admission_mutate": {
            "loggings": [
                {
                    "namespace_selectors": [],
                    "label_selectors":     [],
                    "config": ""
                }
            ]
        }
    }


service:
  type: ClusterIP
  port: 443
  targetPort: 9543

env: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  requests:
     cpu: 100m
     memory: 64Mi
  limits:
     cpu: 500m
     memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
