# Default values for datakit-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  ## @param repository - string - required
  ## Define the repository to use:
  #
  repository: (@REPOSITORY)

  ## @param tag - string - required
  ## Define the Cluster-Agent version to use.
  #
  tag: (@APP_VERSION)

  ## @param pullPolicy - string - optional
  ## The Kubernetes [imagePullPolicy][] value
  #
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "datakit-operator"

serviceAccount:
  create: true
  name: ""

admissionregistration:
  webhooks:
    caBundle: (@CABUNDLE)


configmap:
  jsonconfig: |-
    {
        "server_listen": "0.0.0.0:9543",
        "log_level":     "info",
        "admission_inject_v2": {
            "ddtraces": [
                {
                    "language": "java",
                    "namespace_selectors": ["default"],
                    "label_selectors":     [],
                    "check_annotation":    false,
                    "image":    "(@BRAND_REPO_DATAKIT_OPERATOR)/dd-lib-java-init:v1.60.4-ext",
                    "envs": {
                        "DD_AGENT_HOST":           "datakit-service.datakit.svc.cluster.local",
                        "DD_TRACE_AGENT_PORT":     "9529",
                        "DD_JMXFETCH_STATSD_HOST": "datakit-service.datakit.svc.cluster.local",
                        "DD_JMXFETCH_STATSD_PORT": "8125",
                        "DD_SERVICE":              "{fieldRef:metadata.labels['app']}",
                        "POD_NAME":                "{fieldRef:metadata.name}",
                        "POD_NAMESPACE":           "{fieldRef:metadata.namespace}",
                        "NODE_NAME":               "{fieldRef:spec.nodeName}",
                        "DD_TAGS":                 "pod_name:$(POD_NAME),pod_namespace:$(POD_NAMESPACE),host:$(NODE_NAME)"
                    }
                },
                {
                    "language": "python",
                    "namespace_selectors": ["default"],
                    "label_selectors":     [],
                    "check_annotation":    false,
                    "image":    "(@BRAND_REPO_DATAKIT_OPERATOR)/dd-lib-python-init:v2.21.12",
                    "envs": {
                        "DD_AGENT_HOST":           "datakit-service.datakit.svc.cluster.local",
                        "DD_TRACE_AGENT_PORT":     "9529",
                        "DD_JMXFETCH_STATSD_HOST": "datakit-service.datakit.svc.cluster.local",
                        "DD_JMXFETCH_STATSD_PORT": "8125",
                        "DD_SERVICE":              "{fieldRef:metadata.labels['app']}",
                        "POD_NAME":                "{fieldRef:metadata.name}",
                        "POD_NAMESPACE":           "{fieldRef:metadata.namespace}",
                        "NODE_NAME":               "{fieldRef:spec.nodeName}",
                        "DD_TAGS":                 "pod_name:$(POD_NAME),pod_namespace:$(POD_NAMESPACE),host:$(NODE_NAME)"
                    }
                },
                {
                    "language": "php",
                    "php_loader_flavor": "linux-gnu",
                    "namespace_selectors": ["default"],
                    "label_selectors":     [],
                    "check_annotation":    false,
                    "image":    "(@BRAND_REPO_DATAKIT_OPERATOR)/dd-lib-php-init:1.13.1",
                    "envs": {
                        "DD_AGENT_HOST":           "datakit-service.datakit.svc.cluster.local",
                        "DD_TRACE_AGENT_PORT":     "9529",
                        "DD_SERVICE":              "{fieldRef:metadata.labels['app']}",
                        "POD_NAME":                "{fieldRef:metadata.name}",
                        "POD_NAMESPACE":           "{fieldRef:metadata.namespace}",
                        "NODE_NAME":               "{fieldRef:spec.nodeName}",
                        "DD_TAGS":                 "pod_name:$(POD_NAME),pod_namespace:$(POD_NAMESPACE),host:$(NODE_NAME)"
                    }
                },
                {
                    "language": "nodejs",
                    "namespace_selectors": ["default"],
                    "label_selectors":     [],
                    "check_annotation":    false,
                    "image":    "(@BRAND_REPO_DATAKIT_OPERATOR)/dd-lib-js-init:5.102.0",
                    "envs": {
                        "DD_AGENT_HOST":           "datakit-service.datakit.svc.cluster.local",
                        "DD_TRACE_AGENT_PORT":     "9529",
                        "DD_SERVICE":              "{fieldRef:metadata.labels['app']}",
                        "POD_NAME":                "{fieldRef:metadata.name}",
                        "POD_NAMESPACE":           "{fieldRef:metadata.namespace}",
                        "NODE_NAME":               "{fieldRef:spec.nodeName}",
                        "DD_TAGS":                 "pod_name:$(POD_NAME),pod_namespace:$(POD_NAMESPACE),host:$(NODE_NAME)"
                    }
                }
            ],
            "logfwds": [
                {
                    "namespace_selectors": ["default"],
                    "label_selectors":     [],
                    "image": "(@BRAND_REPO_DATAKIT)/logfwd:1.93.0",
                    "envs": {
                        "LOGFWD_DATAKIT_HOST":              "{fieldRef:status.hostIP}",
                        "LOGFWD_DATAKIT_PORT":              "9533",
                        "LOGFWD_DATAKIT_OPERATOR_ENDPOINT": "datakit-operator.datakit.svc:443",
                        "LOGFWD_GLOBAL_SERVICE":            "{fieldRef:metadata.labels['app']}",
                        "LOGFWD_POD_NAME":                  "{fieldRef:metadata.name}",
                        "LOGFWD_POD_NAMESPACE":             "{fieldRef:metadata.namespace}",
                        "LOGFWD_POD_IP":                    "{fieldRef:status.podIP}"
                    },
                    "resources": {
                        "requests": {
                            "cpu":    "100m",
                            "memory": "128Mi"
                        },
                        "limits": {
                           "cpu":    "200m",
                           "memory": "256Mi"
                        }
                    },
                    "log_configs": "",
                    "log_volume_paths": []
                }
            ],
            "flameshots": [
                {
                    "namespace_selectors": ["default"],
                    "label_selectors":     [],
                    "image": "(@BRAND_REPO_DATAKIT)/flameshot:0.2.1",
                    "envs": {
                        "FLAMESHOT_DATAKIT_ADDR":     "http://datakit-service.datakit:9529/profiling/v1/input",
                        "FLAMESHOT_MONITOR_INTERVAL": "10s",
                        "FLAMESHOT_LOG_LEVEL":        "info",
                        "FLAMESHOT_PROFILING_PATH":   "/flameshot-data",
                        "FLAMESHOT_LOG_PATH":         "/var/log/flameshot.log",
                        "FLAMESHOT_HTTP_LOCAL_PORT":  "8089",
                        "FLAMESHOT_POD_CPU_LIMIT":    "{resourceFieldRef:limits.cpu}",
                        "FLAMESHOT_POD_MEM_LIMIT":    "{resourceFieldRef:limits.memory}"
                    },
                    "resources": {
                        "requests": {
                            "cpu":    "100m",
                            "memory": "128Mi"
                        },
                        "limits": {
                           "cpu":    "200m",
                           "memory": "256Mi"
                        }
                    },
                    "processes": "",
                    "enable_prometheus_annotations": true
                }
            ]
        },
        "admission_mutate": {
            "loggings": [
                {
                    "namespace_selectors": [],
                    "label_selectors":     [],
                    "config": ""
                }
            ]
        }
    }


service:
  type: ClusterIP
  port: 443
  targetPort: 9543

env: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  requests:
     cpu: 100m
     memory: 64Mi
  limits:
     cpu: 500m
     memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
