{{- $serviceAccount := .Values.serviceAccount | default dict }}
{{- if or (not (hasKey $serviceAccount "create")) $serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datakit-operator.serviceAccountName" . }}
{{- end }}
